import { Command } from 'commander';
import pc from 'picocolors';
import { requireConfig } from '../config.js';
import { header, info } from '../utils/display.js';

function generateAnsiblePlaybook(projectId: string, targetHost: string, nodeVersion: string, tier: string): string {
  const lines: string[] = [];

  lines.push('---');
  lines.push('# VibeBetter Ansible Playbook — generated by `vibe ansible`');
  lines.push(`# Project: ${projectId}`);
  lines.push('');
  lines.push('- name: Deploy VibeBetter');
  lines.push(`  hosts: ${targetHost}`);
  lines.push('  become: true');
  lines.push('  vars:');
  lines.push(`    project_id: "${projectId}"`);
  lines.push(`    node_version: "${nodeVersion}"`);
  lines.push(`    tier: "${tier}"`);
  lines.push('    app_dir: /opt/vibebetter');
  lines.push('    app_user: vibebetter');
  lines.push('');
  lines.push('  tasks:');
  lines.push('    - name: Create application user');
  lines.push('      user:');
  lines.push('        name: "{{ app_user }}"');
  lines.push('        system: true');
  lines.push('        shell: /usr/sbin/nologin');
  lines.push('        home: "{{ app_dir }}"');
  lines.push('');
  lines.push('    - name: Install Node.js');
  lines.push('      shell: |');
  lines.push('        curl -fsSL https://deb.nodesource.com/setup_{{ node_version }}.x | bash -');
  lines.push('        apt-get install -y nodejs');
  lines.push('      args:');
  lines.push('        creates: /usr/bin/node');
  lines.push('');
  lines.push('    - name: Install pnpm');
  lines.push('      npm:');
  lines.push('        name: pnpm');
  lines.push('        global: true');
  lines.push('');
  lines.push('    - name: Create application directory');
  lines.push('      file:');
  lines.push('        path: "{{ app_dir }}"');
  lines.push('        state: directory');
  lines.push('        owner: "{{ app_user }}"');
  lines.push('        mode: "0755"');
  lines.push('');
  lines.push('    - name: Clone/update application');
  lines.push('      git:');
  lines.push('        repo: https://github.com/vibebetter/vibebetter.git');
  lines.push('        dest: "{{ app_dir }}"');
  lines.push('        version: main');
  lines.push('      become_user: "{{ app_user }}"');
  lines.push('');
  lines.push('    - name: Install dependencies');
  lines.push('      command: pnpm install --frozen-lockfile');
  lines.push('      args:');
  lines.push('        chdir: "{{ app_dir }}"');
  lines.push('      become_user: "{{ app_user }}"');
  lines.push('');
  lines.push('    - name: Build application');
  lines.push('      command: pnpm build');
  lines.push('      args:');
  lines.push('        chdir: "{{ app_dir }}"');
  lines.push('      become_user: "{{ app_user }}"');
  lines.push('');
  lines.push('    - name: Configure environment');
  lines.push('      template:');
  lines.push('        src: templates/env.j2');
  lines.push('        dest: "{{ app_dir }}/.env"');
  lines.push('        owner: "{{ app_user }}"');
  lines.push('        mode: "0600"');
  lines.push('');
  lines.push('    - name: Create systemd service');
  lines.push('      template:');
  lines.push('        src: templates/vibebetter.service.j2');
  lines.push('        dest: /etc/systemd/system/vibebetter.service');
  lines.push('      notify: Restart VibeBetter');
  lines.push('');
  lines.push('    - name: Enable and start service');
  lines.push('      systemd:');
  lines.push('        name: vibebetter');
  lines.push('        enabled: true');
  lines.push('        state: started');
  lines.push('        daemon_reload: true');

  if (tier === 'enterprise') {
    lines.push('');
    lines.push('    - name: Configure worker service');
    lines.push('      template:');
    lines.push('        src: templates/vibebetter-worker.service.j2');
    lines.push('        dest: /etc/systemd/system/vibebetter-worker.service');
    lines.push('');
    lines.push('    - name: Enable worker service');
    lines.push('      systemd:');
    lines.push('        name: vibebetter-worker');
    lines.push('        enabled: true');
    lines.push('        state: started');
  }

  lines.push('');
  lines.push('  handlers:');
  lines.push('    - name: Restart VibeBetter');
  lines.push('      systemd:');
  lines.push('        name: vibebetter');
  lines.push('        state: restarted');

  return lines.join('\n');
}

export const ansibleCommand = new Command('ansible')
  .description('Generate Ansible playbook for VibeBetter deployment')
  .option('--host <host>', 'Target host group', 'vibebetter_servers')
  .option('--node-version <version>', 'Node.js major version', '20')
  .option('--tier <tier>', 'Deployment tier (free, pro, enterprise)', 'pro')
  .option('--output <file>', 'Write to file instead of stdout')
  .action(async (opts) => {
    header('Ansible Playbook Generator');

    const config = requireConfig();
    const projectId = config.projectId ?? 'default';

    const playbook = generateAnsiblePlaybook(projectId, opts.host, opts.nodeVersion, opts.tier);

    if (opts.output) {
      const fs = await import('node:fs');
      fs.writeFileSync(opts.output, playbook, 'utf-8');
      info(`Written to ${pc.bold(opts.output)}`);
    } else {
      console.log(playbook);
    }

    console.log();
    info('Run with: ansible-playbook -i inventory playbook.yml');
  });
