import { Command } from 'commander';
import pc from 'picocolors';
import { requireConfig } from '../config.js';
import { header, info } from '../utils/display.js';

function generateArgoCD(projectId: string, repoUrl: string, targetRevision: string, namespace: string, path: string): string {
  return `# ArgoCD Application Manifest — generated by \`vibe argocd\`
# Project: ${projectId}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vibebetter-${projectId}
  namespace: argocd
  labels:
    app.kubernetes.io/name: vibebetter
    app.kubernetes.io/part-of: vibebetter
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ${repoUrl}
    targetRevision: ${targetRevision}
    path: ${path}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${namespace}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
`;
}

export const argocdCommand = new Command('argocd')
  .description('Generate ArgoCD application manifest')
  .option('--repo <url>', 'Git repository URL', 'https://github.com/org/vibebetter.git')
  .option('--revision <rev>', 'Target revision', 'main')
  .option('--namespace <ns>', 'Target namespace', 'vibebetter')
  .option('--path <path>', 'Path to k8s manifests in repo', 'k8s/')
  .option('--output <file>', 'Write to file instead of stdout')
  .action(async (opts) => {
    header('ArgoCD Manifest Generator');

    const config = requireConfig();
    const projectId = config.projectId ?? 'default';
    const manifest = generateArgoCD(projectId, opts.repo, opts.revision, opts.namespace, opts.path);

    if (opts.output) {
      const fs = await import('node:fs');
      fs.writeFileSync(opts.output, manifest, 'utf-8');
      info(`Written to ${pc.bold(opts.output)}`);
    } else {
      console.log(manifest);
    }

    console.log();
    info('Apply with: kubectl apply -f <file> -n argocd');
  });
