import { Command } from 'commander';
import pc from 'picocolors';
import { requireConfig } from '../config.js';
import { ApiClient } from '../api-client.js';
import { header, info } from '../utils/display.js';

interface AzureDevOpsTask {
  task: string;
  displayName: string;
  inputs: Record<string, string>;
}

interface AzurePipelineConfig {
  trigger: string[];
  pool: { vmImage: string };
  steps: AzureDevOpsTask[];
}

function generateAzurePipeline(threshold: number): AzurePipelineConfig {
  return {
    trigger: ['main', 'develop'],
    pool: { vmImage: 'ubuntu-latest' },
    steps: [
      { task: 'NodeTool@0', displayName: 'Use Node.js', inputs: { versionSpec: '20.x' } },
      { task: 'CmdLine@2', displayName: 'Install VibeBetter CLI', inputs: { script: 'npm install -g @vibebetter/cli' } },
      { task: 'CmdLine@2', displayName: 'Run VibeBetter Check', inputs: { script: `vibe ci --format json --threshold ${threshold}` } },
      { task: 'PublishTestResults@2', displayName: 'Publish Results', inputs: { testResultsFormat: 'JUnit', testResultsFiles: '**/vibe-report.xml', mergeTestResults: 'true' } },
    ],
  };
}

function toYaml(obj: unknown, indent: number = 0): string {
  const pad = ' '.repeat(indent);
  if (Array.isArray(obj)) {
    return obj.map((item) => {
      if (typeof item === 'object' && item !== null) {
        const lines = toYaml(item, indent + 2).trim();
        return `${pad}- ${lines.replace(new RegExp(`^\\s{${indent + 2}}`), '')}`;
      }
      return `${pad}- ${item}`;
    }).join('\n');
  }
  if (typeof obj === 'object' && obj !== null) {
    return Object.entries(obj).map(([k, v]) => {
      if (typeof v === 'object' && v !== null) {
        return `${pad}${k}:\n${toYaml(v, indent + 2)}`;
      }
      return `${pad}${k}: ${v}`;
    }).join('\n');
  }
  return `${pad}${obj}`;
}

export const azureCommand = new Command('azure')
  .description('Format output for Azure DevOps integration')
  .option('--threshold <n>', 'PSRI threshold', '0.6')
  .option('--stdout', 'Print pipeline YAML to stdout')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    header('Azure DevOps Integration');
    const threshold = parseFloat(opts.threshold);

    if (opts.stdout || opts.json) {
      const pipeline = generateAzurePipeline(threshold);
      if (opts.json) {
        console.log(JSON.stringify(pipeline, null, 2));
      } else {
        console.log(`# Azure DevOps Pipeline — VibeBetter Integration`);
        console.log(`# Generated by: vibe azure`);
        console.log(toYaml(pipeline));
      }
      return;
    }

    const config = requireConfig();
    const client = new ApiClient(config);

    const overview = await client.getOverview().catch(() => null);
    if (!overview) {
      info('No metrics available. Run: vibe sync');
      const pipeline = generateAzurePipeline(threshold);
      console.log(pc.bold('\n  Generated azure-pipelines.yml:\n'));
      console.log(pc.dim(toYaml(pipeline, 2)));
      return;
    }

    const psri = overview.psriScore ?? 0;
    const passed = psri <= threshold;

    console.log(pc.bold('  Azure DevOps Report\n'));
    console.log(`  ${pc.dim('Status:')} ${passed ? pc.green('PASSED') : pc.red('FAILED')}`);
    console.log(`  ${pc.dim('PSRI:')} ${psri.toFixed(3)} / ${threshold}`);
    console.log(`  ${pc.dim('TDI:')} ${(overview.tdiScore ?? 0).toFixed(3)}`);
    console.log(`  ${pc.dim('Hotspots:')} ${overview.hotspotFiles ?? 0}`);
    console.log();

    console.log(pc.bold('  Pipeline YAML:\n'));
    const pipeline = generateAzurePipeline(threshold);
    console.log(pc.dim(toYaml(pipeline, 2)));
    console.log();
    info('Copy the YAML to azure-pipelines.yml in your repository root');
  });
