import { Command } from 'commander';
import pc from 'picocolors';
import { requireConfig } from '../config.js';
import { header, info } from '../utils/display.js';

function generateBackstageCatalog(projectId: string, name: string, owner: string, lifecycle: string): string {
  return `# Backstage Catalog Entry — generated by \`vibe backstage\`
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${name}
  description: VibeBetter AI Coding Insight Platform
  annotations:
    github.com/project-slug: ${owner}/${name}
    vibebetter.io/project-id: "${projectId}"
    backstage.io/techdocs-ref: dir:.
  tags:
    - typescript
    - ai-coding
    - metrics
    - nodejs
  links:
    - url: https://vibebetter.io
      title: VibeBetter Dashboard
      icon: dashboard
spec:
  type: service
  lifecycle: ${lifecycle}
  owner: ${owner}
  system: vibebetter
  providesApis:
    - vibebetter-api
  dependsOn:
    - resource:default/vibebetter-db
    - resource:default/vibebetter-redis
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: vibebetter-api
  description: VibeBetter REST API for AI coding metrics
spec:
  type: openapi
  lifecycle: ${lifecycle}
  owner: ${owner}
  definition: |
    openapi: "3.0.0"
    info:
      title: VibeBetter API
      version: "1.0"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vibebetter-db
  description: VibeBetter PostgreSQL database
spec:
  type: database
  owner: ${owner}
  system: vibebetter
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vibebetter-redis
  description: VibeBetter Redis cache
spec:
  type: cache
  owner: ${owner}
  system: vibebetter
`;
}

export const backstageCommand = new Command('backstage')
  .description('Generate Backstage catalog entry for the project')
  .option('--name <name>', 'Component name', 'vibebetter')
  .option('--owner <owner>', 'Owner team/user', 'engineering')
  .option('--lifecycle <lc>', 'Lifecycle stage (experimental, production)', 'production')
  .option('--output <file>', 'Write to file instead of stdout')
  .action(async (opts) => {
    header('Backstage Catalog Generator');

    const config = requireConfig();
    const projectId = config.projectId ?? 'default';
    const catalog = generateBackstageCatalog(projectId, opts.name, opts.owner, opts.lifecycle);

    if (opts.output) {
      const fs = await import('node:fs');
      fs.writeFileSync(opts.output, catalog, 'utf-8');
      info(`Written to ${pc.bold(opts.output)}`);
    } else {
      console.log(catalog);
    }

    console.log();
    info('Place this file as catalog-info.yaml in your repo root.');
  });
