import { Command } from 'commander';
import pc from 'picocolors';
import { execSync } from 'child_process';
import { header, info } from '../utils/display.js';

const AI_PATTERNS = [
  'copilot', 'cursor', 'ai-generated', 'ai-assisted', 'llm',
  'gpt', 'claude', 'ai:', 'generated by',
];

export const changelogCommand = new Command('changelog')
  .description('List recent commits with AI detection')
  .option('-n, --count <number>', 'Number of commits to show', '20')
  .action(async (opts) => {
    header('Changelog — Recent Commits');
    const count = parseInt(opts.count, 10) || 20;

    try {
      const log = execSync(
        `git log --oneline --format="%H|%s|%an|%ar" -n ${count}`,
        { encoding: 'utf-8' },
      ).trim();

      if (!log) {
        info('No commits found.');
        return;
      }

      for (const line of log.split('\n')) {
        const [hash, message, author, date] = line.split('|');
        const shortHash = hash?.slice(0, 7) ?? '';
        const isAi = AI_PATTERNS.some((p) =>
          (message ?? '').toLowerCase().includes(p) ||
          (author ?? '').toLowerCase().includes(p),
        );
        const tag = isAi ? pc.magenta(' [AI]') : '';
        console.log(
          `  ${pc.dim(shortHash)} ${message}${tag} ${pc.dim(`— ${author}, ${date}`)}`,
        );
      }

      console.log();
    } catch {
      console.log(pc.red('  Failed to read git log. Is this a git repository?'));
    }
  });
