import { Command } from 'commander';
import pc from 'picocolors';
import { requireConfig } from '../config.js';
import { header, info } from '../utils/display.js';

function generateChromaticConfig(projectId: string, framework: string, ci: string): string {
  const lines: string[] = [];

  lines.push('// VibeBetter Visual Regression Test Config');
  lines.push(`// Generated by \`vibe chromatic\` for project: ${projectId}`);
  lines.push('');
  lines.push('/** @type {import("chromatic").ChromaticConfig} */');
  lines.push('module.exports = {');
  lines.push(`  projectToken: process.env.CHROMATIC_PROJECT_TOKEN || "",`);
  lines.push(`  buildScriptName: "build-storybook",`);
  lines.push(`  exitZeroOnChanges: true,`);
  lines.push(`  exitOnceUploaded: false,`);
  lines.push(`  autoAcceptChanges: "main",`);
  lines.push(`  onlyChanged: true,`);
  lines.push(`  externals: ["public/**"],`);
  lines.push(`  skip: "dependabot/**",`);
  lines.push('};');

  if (ci === 'github') {
    lines.push('');
    lines.push('// --- GitHub Actions workflow (chromatic.yml) ---');
    lines.push('// name: Chromatic');
    lines.push('// on: push');
    lines.push('// jobs:');
    lines.push('//   chromatic:');
    lines.push('//     runs-on: ubuntu-latest');
    lines.push('//     steps:');
    lines.push('//       - uses: actions/checkout@v4');
    lines.push('//         with: { fetch-depth: 0 }');
    lines.push('//       - uses: actions/setup-node@v4');
    lines.push('//       - run: pnpm install --frozen-lockfile');
    lines.push(`//       - uses: chromaui/action@latest`);
    lines.push('//         with:');
    lines.push('//           projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}');
  }

  if (framework === 'storybook') {
    lines.push('');
    lines.push('// --- Storybook config (.storybook/main.ts) ---');
    lines.push('// import type { StorybookConfig } from "@storybook/react-vite";');
    lines.push('// const config: StorybookConfig = {');
    lines.push('//   stories: ["../src/**/*.stories.@(ts|tsx)"],');
    lines.push('//   framework: "@storybook/react-vite",');
    lines.push('// };');
    lines.push('// export default config;');
  }

  return lines.join('\n');
}

export const chromaticCommand = new Command('chromatic')
  .description('Generate visual regression test configuration (Chromatic/Storybook)')
  .option('--framework <fw>', 'UI framework (storybook, playwright)', 'storybook')
  .option('--ci <ci>', 'CI provider (github, gitlab)', 'github')
  .option('--output <file>', 'Write to file instead of stdout')
  .action(async (opts) => {
    header('Visual Regression Test Config');

    const config = requireConfig();
    const projectId = config.projectId ?? 'default';

    const output = generateChromaticConfig(projectId, opts.framework, opts.ci);

    if (opts.output) {
      const fs = await import('node:fs');
      fs.writeFileSync(opts.output, output, 'utf-8');
      info(`Written to ${pc.bold(opts.output)}`);
    } else {
      console.log(output);
    }

    console.log();
    info('Set CHROMATIC_PROJECT_TOKEN env var before running.');
    info('Run: npx chromatic');
  });
