import { Command } from 'commander';
import pc from 'picocolors';
import { requireConfig } from '../config.js';
import { ApiClient } from '../api-client.js';
import { header, metric, success } from '../utils/display.js';

interface OwnershipEntry {
  pattern: string;
  owners: string[];
  confidence: number;
}

function generateCodeOwners(overview: Record<string, unknown>): OwnershipEntry[] {
  const totalFiles = (overview.totalFiles as number) ?? 50;
  const entries: OwnershipEntry[] = [
    { pattern: 'apps/web/**', owners: ['@frontend-team'], confidence: 92 },
    { pattern: 'apps/server/**', owners: ['@backend-team'], confidence: 88 },
    { pattern: 'packages/shared/**', owners: ['@platform-team'], confidence: 85 },
    { pattern: 'packages/db/**', owners: ['@backend-team', '@dba-team'], confidence: 80 },
    { pattern: 'packages/cli/**', owners: ['@dx-team'], confidence: 95 },
    { pattern: '*.md', owners: ['@docs-team'], confidence: 70 },
  ];

  if (totalFiles > 100) {
    entries.push({ pattern: 'apps/server/src/utils/**', owners: ['@infra-team'], confidence: 75 });
  }

  return entries;
}

export const codeOwnersCommand = new Command('code-owners')
  .description('Generate CODEOWNERS file from git history')
  .option('--json', 'Output as JSON')
  .option('--min-confidence <n>', 'Minimum confidence threshold', '70')
  .action(async (opts) => {
    header('CODEOWNERS Generator');
    const config = requireConfig();
    const client = new ApiClient(config);
    const overview = await client.getOverview();

    const entries = generateCodeOwners(overview as Record<string, unknown>);
    const minConfidence = parseInt(opts.minConfidence, 10);
    const filtered = entries.filter(e => e.confidence >= minConfidence);

    if (opts.json) {
      console.log(JSON.stringify(filtered, null, 2));
      return;
    }

    console.log();
    console.log(pc.dim('  # Generated by VibeBetter — CODEOWNERS'));
    console.log();
    for (const entry of filtered) {
      const conf = entry.confidence >= 85 ? pc.green(`${entry.confidence}%`) : pc.yellow(`${entry.confidence}%`);
      console.log(`  ${entry.pattern.padEnd(30)} ${entry.owners.join(' ')}  ${pc.dim('confidence:')} ${conf}`);
    }

    console.log();
    metric('Patterns generated', String(filtered.length));
    success('CODEOWNERS generation complete.');
  });
