import { Command } from 'commander';
import pc from 'picocolors';
import { requireConfig } from '../config.js';
import { header, info } from '../utils/display.js';

function generateDockerCompose(projectId: string, includeMonitoring: boolean, tier: string): string {
  const lines: string[] = [];

  lines.push('# VibeBetter Stack — generated by `vibe compose`');
  lines.push(`# Project: ${projectId}`);
  lines.push('');
  lines.push('services:');
  lines.push('  server:');
  lines.push('    image: vibebetter/server:latest');
  lines.push('    ports:');
  lines.push('      - "3001:3001"');
  lines.push('    environment:');
  lines.push('      NODE_ENV: production');
  lines.push('      DATABASE_URL: postgres://vibebetter:vibebetter@postgres:5432/vibebetter');
  lines.push('      REDIS_URL: redis://redis:6379');
  lines.push(`      VIBEBETTER_PROJECT_ID: "${projectId}"`);
  lines.push('    depends_on:');
  lines.push('      postgres:');
  lines.push('        condition: service_healthy');
  lines.push('      redis:');
  lines.push('        condition: service_healthy');
  lines.push('    restart: unless-stopped');
  lines.push('');
  lines.push('  web:');
  lines.push('    image: vibebetter/web:latest');
  lines.push('    ports:');
  lines.push('      - "3000:3000"');
  lines.push('    environment:');
  lines.push('      NEXT_PUBLIC_API_URL: http://server:3001');
  lines.push('    depends_on:');
  lines.push('      - server');
  lines.push('    restart: unless-stopped');
  lines.push('');
  lines.push('  postgres:');
  lines.push('    image: postgres:16-alpine');
  lines.push('    environment:');
  lines.push('      POSTGRES_DB: vibebetter');
  lines.push('      POSTGRES_USER: vibebetter');
  lines.push('      POSTGRES_PASSWORD: vibebetter');
  lines.push('    volumes:');
  lines.push('      - pg_data:/var/lib/postgresql/data');
  lines.push('    ports:');
  lines.push('      - "5432:5432"');
  lines.push('    healthcheck:');
  lines.push('      test: ["CMD-SHELL", "pg_isready -U vibebetter"]');
  lines.push('      interval: 5s');
  lines.push('      timeout: 3s');
  lines.push('      retries: 5');
  lines.push('');
  lines.push('  redis:');
  lines.push('    image: redis:7-alpine');
  lines.push('    ports:');
  lines.push('      - "6379:6379"');
  lines.push('    healthcheck:');
  lines.push('      test: ["CMD", "redis-cli", "ping"]');
  lines.push('      interval: 5s');
  lines.push('      timeout: 3s');
  lines.push('      retries: 5');
  lines.push('    volumes:');
  lines.push('      - redis_data:/data');

  if (tier === 'enterprise') {
    lines.push('');
    lines.push('  worker:');
    lines.push('    image: vibebetter/server:latest');
    lines.push('    command: ["node", "dist/worker.js"]');
    lines.push('    environment:');
    lines.push('      DATABASE_URL: postgres://vibebetter:vibebetter@postgres:5432/vibebetter');
    lines.push('      REDIS_URL: redis://redis:6379');
    lines.push('    depends_on:');
    lines.push('      - postgres');
    lines.push('      - redis');
    lines.push('    restart: unless-stopped');
  }

  if (includeMonitoring) {
    lines.push('');
    lines.push('  prometheus:');
    lines.push('    image: prom/prometheus:latest');
    lines.push('    ports:');
    lines.push('      - "9090:9090"');
    lines.push('    volumes:');
    lines.push('      - ./prometheus.yml:/etc/prometheus/prometheus.yml');
    lines.push('');
    lines.push('  grafana:');
    lines.push('    image: grafana/grafana:latest');
    lines.push('    ports:');
    lines.push('      - "3002:3000"');
    lines.push('    environment:');
    lines.push('      GF_SECURITY_ADMIN_PASSWORD: admin');
    lines.push('    depends_on:');
    lines.push('      - prometheus');
  }

  lines.push('');
  lines.push('volumes:');
  lines.push('  pg_data:');
  lines.push('  redis_data:');

  return lines.join('\n');
}

export const composeCommand = new Command('compose')
  .description('Generate docker-compose.yml for full VibeBetter stack')
  .option('--tier <tier>', 'Deployment tier (free, pro, enterprise)', 'pro')
  .option('--monitoring', 'Include Prometheus + Grafana', false)
  .option('--output <file>', 'Write to file', 'docker-compose.generated.yml')
  .action(async (opts) => {
    header('Docker Compose Generator');

    const config = requireConfig();
    const projectId = config.projectId ?? 'default';

    const yml = generateDockerCompose(projectId, opts.monitoring, opts.tier);

    if (opts.output) {
      const fs = await import('node:fs');
      fs.writeFileSync(opts.output, yml, 'utf-8');
      info(`Written to ${pc.bold(opts.output)}`);
    } else {
      console.log(yml);
    }

    console.log();
    info(`Tier: ${pc.bold(opts.tier)}`);
    info(`Monitoring: ${opts.monitoring ? pc.green('enabled') : pc.dim('disabled')}`);
    info('Start with: docker compose -f docker-compose.generated.yml up -d');
  });
