import { Command } from 'commander';
import pc from 'picocolors';
import { requireConfig } from '../config.js';
import { ApiClient } from '../api-client.js';
import { header, info } from '../utils/display.js';

function buildEmailHtml(projectId: string, overview: Record<string, unknown>): string {
  const psri = Number(overview.psriScore ?? 0).toFixed(1);
  const tdi = Number(overview.tdiScore ?? 0).toFixed(1);
  const hotspots = Number(overview.hotspotFiles ?? 0);
  const totalFiles = Number(overview.totalFiles ?? 0);
  const aiSuccess = Number(overview.aiSuccessRate ?? 0).toFixed(1);
  const totalPrs = Number(overview.totalPrs ?? 0);

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width"></head>
<body style="margin:0;padding:0;background:#09090b;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<div style="max-width:600px;margin:0 auto;padding:24px;">
  <div style="background:#18181b;border:1px solid #27272a;border-radius:12px;padding:24px;margin-bottom:16px;">
    <h1 style="color:#f4f4f5;font-size:20px;margin:0 0 4px;">VibeBetter Report</h1>
    <p style="color:#71717a;font-size:13px;margin:0;">Project: ${projectId}</p>
  </div>
  <div style="display:flex;gap:12px;margin-bottom:16px;">
    <div style="flex:1;background:#18181b;border:1px solid #27272a;border-radius:8px;padding:16px;text-align:center;">
      <div style="color:#818cf8;font-size:24px;font-weight:700;">${psri}</div>
      <div style="color:#71717a;font-size:11px;margin-top:4px;">PSRI</div>
    </div>
    <div style="flex:1;background:#18181b;border:1px solid #27272a;border-radius:8px;padding:16px;text-align:center;">
      <div style="color:#fbbf24;font-size:24px;font-weight:700;">${tdi}</div>
      <div style="color:#71717a;font-size:11px;margin-top:4px;">TDI</div>
    </div>
    <div style="flex:1;background:#18181b;border:1px solid #27272a;border-radius:8px;padding:16px;text-align:center;">
      <div style="color:#34d399;font-size:24px;font-weight:700;">${aiSuccess}%</div>
      <div style="color:#71717a;font-size:11px;margin-top:4px;">AI Success</div>
    </div>
  </div>
  <div style="background:#18181b;border:1px solid #27272a;border-radius:8px;padding:16px;">
    <table style="width:100%;border-collapse:collapse;font-size:13px;">
      <tr><td style="color:#a1a1aa;padding:6px 0;">Total Files</td><td style="color:#f4f4f5;text-align:right;padding:6px 0;">${totalFiles}</td></tr>
      <tr><td style="color:#a1a1aa;padding:6px 0;">Hotspot Files</td><td style="color:#f4f4f5;text-align:right;padding:6px 0;">${hotspots}</td></tr>
      <tr><td style="color:#a1a1aa;padding:6px 0;">Total PRs</td><td style="color:#f4f4f5;text-align:right;padding:6px 0;">${totalPrs}</td></tr>
    </table>
  </div>
  <p style="color:#52525b;font-size:11px;text-align:center;margin-top:24px;">Generated by VibeBetter CLI</p>
</div>
</body>
</html>`;
}

export const emailReportCommand = new Command('email-report')
  .description('Generate HTML email body for metric reports')
  .option('--output <file>', 'Write HTML to file')
  .option('--project-key <key>', 'Custom project identifier')
  .action(async (opts) => {
    header('Email Report');

    const config = requireConfig();
    const client = new ApiClient(config);
    const overview = await client.getOverview().catch(() => null);

    if (!overview) {
      info('No metrics available. Run: vibe sync');
      return;
    }

    const data = overview as Record<string, unknown>;
    const projectId = opts.projectKey ?? config.projectId ?? 'default';
    const html = buildEmailHtml(projectId, data);

    if (opts.output) {
      const fs = await import('node:fs');
      fs.writeFileSync(opts.output, html, 'utf-8');
      info(`Email HTML written to ${pc.bold(opts.output)}`);
    } else {
      console.log(html);
    }

    console.log();
    info('Copy this HTML into your email template or send via API');
  });
