import { Command } from 'commander';
import pc from 'picocolors';
import { header, info } from '../utils/display.js';

interface GitLabCIConfig {
  stages: string[];
  image: string;
  threshold: number;
  allowFailure: boolean;
}

const DEFAULT_CONFIG: GitLabCIConfig = {
  stages: ['test', 'vibe-check'],
  image: 'node:20-alpine',
  threshold: 0.6,
  allowFailure: false,
};

function generateGitLabCI(config: GitLabCIConfig): string {
  const lines: string[] = [
    '# VibeBetter GitLab CI Integration',
    `# Generated by: vibe gitlab-ci`,
    `# Threshold: ${config.threshold}`,
    '',
    'stages:',
    ...config.stages.map((s) => `  - ${s}`),
    '',
    'vibe-check:',
    `  stage: vibe-check`,
    `  image: ${config.image}`,
    `  allow_failure: ${config.allowFailure}`,
    '  before_script:',
    '    - npm install -g @vibebetter/cli',
    '  script:',
    '    - vibe ci --format json --threshold ${VIBE_THRESHOLD:-' + config.threshold + '}',
    '  artifacts:',
    '    reports:',
    '      codequality: vibe-report.json',
    '    paths:',
    '      - vibe-report.json',
    '  rules:',
    '    - if: $CI_PIPELINE_SOURCE == "merge_request_event"',
    '    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH',
  ];

  return lines.join('\n');
}

export const gitlabCiCommand = new Command('gitlab-ci')
  .description('Generate .gitlab-ci.yml with VibeBetter integration')
  .option('--threshold <n>', 'PSRI threshold for pass/fail', '0.6')
  .option('--allow-failure', 'Allow vibe-check to fail without blocking pipeline')
  .option('--image <image>', 'Docker image for CI job', 'node:20-alpine')
  .option('--stdout', 'Print to stdout instead of writing file')
  .action(async (opts) => {
    header('GitLab CI Generator');

    const config: GitLabCIConfig = {
      ...DEFAULT_CONFIG,
      threshold: parseFloat(opts.threshold),
      allowFailure: opts.allowFailure ?? false,
      image: opts.image,
    };

    const yaml = generateGitLabCI(config);

    if (opts.stdout) {
      console.log(yaml);
      return;
    }

    console.log(pc.bold('  Generated .gitlab-ci.yml configuration:\n'));
    console.log(pc.dim(yaml.split('\n').map((l) => `  ${l}`).join('\n')));
    console.log();
    info('Copy the output above to your .gitlab-ci.yml file');
    console.log(pc.dim(`  Threshold: ${pc.yellow(String(config.threshold))} | Allow failure: ${config.allowFailure ? pc.green('yes') : pc.red('no')}`));
  });
