import { Command } from 'commander';
import pc from 'picocolors';
import { requireConfig } from '../config.js';
import { header, info } from '../utils/display.js';

function generateHelmValues(projectId: string, replicas: number, tag: string, tier: string): string {
  const lines: string[] = [];

  lines.push('# VibeBetter Helm Values — generated by `vibe helm`');
  lines.push(`# Project: ${projectId}`);
  lines.push(`# Tier: ${tier}`);
  lines.push('');
  lines.push('replicaCount: ' + replicas);
  lines.push('');
  lines.push('image:');
  lines.push('  repository: vibebetter/server');
  lines.push(`  tag: "${tag}"`);
  lines.push('  pullPolicy: IfNotPresent');
  lines.push('');
  lines.push('service:');
  lines.push('  type: ClusterIP');
  lines.push('  port: 80');
  lines.push('  targetPort: 3001');
  lines.push('');
  lines.push('ingress:');
  lines.push('  enabled: true');
  lines.push('  className: nginx');
  lines.push('  annotations:');
  lines.push('    nginx.ingress.kubernetes.io/rate-limit: "100"');
  lines.push('    cert-manager.io/cluster-issuer: letsencrypt-prod');
  lines.push('  hosts:');
  lines.push(`    - host: ${projectId}.vibebetter.dev`);
  lines.push('      paths:');
  lines.push('        - path: /');
  lines.push('          pathType: Prefix');
  lines.push('  tls:');
  lines.push(`    - secretName: ${projectId}-tls`);
  lines.push('      hosts:');
  lines.push(`        - ${projectId}.vibebetter.dev`);
  lines.push('');
  lines.push('resources:');
  lines.push('  requests:');
  lines.push(`    cpu: ${tier === 'enterprise' ? '500m' : '250m'}`);
  lines.push(`    memory: ${tier === 'enterprise' ? '512Mi' : '256Mi'}`);
  lines.push('  limits:');
  lines.push(`    cpu: ${tier === 'enterprise' ? '2' : '1'}`);
  lines.push(`    memory: ${tier === 'enterprise' ? '1Gi' : '512Mi'}`);
  lines.push('');
  lines.push('env:');
  lines.push('  NODE_ENV: production');
  lines.push(`  VIBEBETTER_PROJECT_ID: "${projectId}"`);
  lines.push('');
  lines.push('secrets:');
  lines.push('  DATABASE_URL: ""');
  lines.push('  REDIS_URL: ""');
  lines.push('  JWT_SECRET: ""');
  lines.push('');
  lines.push('postgresql:');
  lines.push('  enabled: true');
  lines.push('  auth:');
  lines.push('    database: vibebetter');
  lines.push('');
  lines.push('redis:');
  lines.push('  enabled: true');
  lines.push('  architecture: standalone');

  return lines.join('\n');
}

export const helmCommand = new Command('helm')
  .description('Generate Helm chart values for VibeBetter deployment')
  .option('--replicas <n>', 'Number of replicas', '2')
  .option('--tag <tag>', 'Image tag', 'latest')
  .option('--tier <tier>', 'Deployment tier (free, pro, enterprise)', 'pro')
  .option('--output <file>', 'Write to file instead of stdout')
  .action(async (opts) => {
    header('Helm Chart Values');

    const config = requireConfig();
    const projectId = config.projectId ?? 'default';
    const values = generateHelmValues(projectId, parseInt(opts.replicas), opts.tag, opts.tier);

    if (opts.output) {
      const fs = await import('node:fs');
      fs.writeFileSync(opts.output, values, 'utf-8');
      info(`Written to ${pc.bold(opts.output)}`);
    } else {
      console.log(values);
    }

    console.log();
    info('Install with: helm install vibebetter ./chart -f values.yaml');
  });
