import { Command } from 'commander';
import pc from 'picocolors';
import { requireConfig } from '../config.js';
import { header, info } from '../utils/display.js';

function generateJenkinsfile(projectId: string, nodeVersion: string, schedule: string): string {
  const lines: string[] = [];

  lines.push('// VibeBetter Jenkins Pipeline — generated by `vibe jenkins`');
  lines.push(`// Project: ${projectId}`);
  lines.push('');
  lines.push('pipeline {');
  lines.push('  agent any');
  lines.push('');
  lines.push('  triggers {');
  lines.push(`    cron('${schedule}')`);
  lines.push('  }');
  lines.push('');
  lines.push('  tools {');
  lines.push(`    nodejs '${nodeVersion}'`);
  lines.push('  }');
  lines.push('');
  lines.push('  environment {');
  lines.push(`    VIBE_PROJECT_ID = '${projectId}'`);
  lines.push('    VIBE_SERVER     = credentials(\'vibe-server-url\')');
  lines.push('    VIBE_TOKEN      = credentials(\'vibe-api-token\')');
  lines.push('  }');
  lines.push('');
  lines.push('  stages {');
  lines.push('    stage(\'Install\') {');
  lines.push('      steps {');
  lines.push('        sh \'npm install -g @vibebetter/cli\'');
  lines.push('      }');
  lines.push('    }');
  lines.push('');
  lines.push('    stage(\'Collect\') {');
  lines.push('      steps {');
  lines.push('        sh \'vibe sync\'');
  lines.push('      }');
  lines.push('    }');
  lines.push('');
  lines.push('    stage(\'Check\') {');
  lines.push('      steps {');
  lines.push('        sh \'vibe check --ci --format json > vibe-report.json\'');
  lines.push('      }');
  lines.push('    }');
  lines.push('');
  lines.push('    stage(\'Report\') {');
  lines.push('      steps {');
  lines.push('        sh \'vibe report --format html --output vibe-report.html\'');
  lines.push('        archiveArtifacts artifacts: \'vibe-report.*\', fingerprint: true');
  lines.push('      }');
  lines.push('    }');
  lines.push('  }');
  lines.push('');
  lines.push('  post {');
  lines.push('    always {');
  lines.push('      echo \'VibeBetter pipeline complete\'');
  lines.push('    }');
  lines.push('    failure {');
  lines.push('      echo \'VibeBetter check detected regressions\'');
  lines.push('    }');
  lines.push('  }');
  lines.push('}');

  return lines.join('\n');
}

export const jenkinsCommand = new Command('jenkins')
  .description('Generate Jenkins pipeline snippet for VibeBetter integration')
  .option('--node <version>', 'Node.js tool name', 'NodeJS-20')
  .option('--schedule <cron>', 'Cron trigger schedule', 'H 2 * * 1-5')
  .option('--output <file>', 'Write to file instead of stdout')
  .action(async (opts) => {
    header('Jenkins Pipeline Generator');

    const config = requireConfig();
    const projectId = config.projectId ?? 'default';
    const jenkinsfile = generateJenkinsfile(projectId, opts.node, opts.schedule);

    if (opts.output) {
      const fs = await import('node:fs');
      fs.writeFileSync(opts.output, jenkinsfile, 'utf-8');
      info(`Written to ${pc.bold(opts.output)}`);
    } else {
      console.log(jenkinsfile);
    }

    console.log();
    info('Add this as a Jenkinsfile in your repo or paste into a pipeline job.');
  });
