import { Command } from 'commander';
import pc from 'picocolors';
import { requireConfig } from '../config.js';
import { ApiClient } from '../api-client.js';
import { header, info, success, riskBadge } from '../utils/display.js';

function buildJiraDescription(
  overview: {
    psriScore: number | null;
    tdiScore: number | null;
    aiSuccessRate: number | null;
    totalPrs: number;
    hotspotFiles: number;
  },
  hotspots: Array<{ filePath: string; riskScore: number; cyclomaticComplexity: number }>,
): string {
  const lines: string[] = [];
  lines.push('h2. VibeBetter Risk Report');
  lines.push('');
  lines.push('||Metric||Value||');
  lines.push(`|PSRI Score|${overview.psriScore?.toFixed(3) ?? 'N/A'}|`);
  lines.push(`|TDI Score|${overview.tdiScore?.toFixed(3) ?? 'N/A'}|`);
  lines.push(`|AI Success Rate|${overview.aiSuccessRate ? `${(overview.aiSuccessRate * 100).toFixed(1)}%` : 'N/A'}|`);
  lines.push(`|Total PRs|${overview.totalPrs}|`);
  lines.push(`|Hotspot Files|${overview.hotspotFiles}|`);

  if (hotspots.length > 0) {
    lines.push('');
    lines.push('h3. Top Risk Files');
    lines.push('||File||Risk||Complexity||');
    for (const f of hotspots.slice(0, 10)) {
      lines.push(`|{{${f.filePath}}}|${Math.round(f.riskScore)}|${f.cyclomaticComplexity}|`);
    }
  }

  lines.push('');
  lines.push('_Generated by VibeBetter CLI_');
  return lines.join('\n');
}

export const jiraCommand = new Command('jira')
  .description('Format risk report for Jira ticket creation')
  .option('--project-key <key>', 'Jira project key', 'ENG')
  .option('--issue-type <type>', 'Issue type', 'Task')
  .option('--json', 'Output as JSON for API')
  .action(async (opts) => {
    header('Jira Report');
    const config = requireConfig();
    const client = new ApiClient(config);

    const overview = await client.getOverview().catch(() => null);
    if (!overview) {
      info('No metrics available. Run: vibe sync');
      return;
    }

    const files = await client.getTopFiles(10).catch(() => []) || [];
    const description = buildJiraDescription(overview, files);

    const psri = overview.psriScore ?? 0;
    const priority = psri > 0.6 ? 'High' : psri > 0.3 ? 'Medium' : 'Low';
    const summary = `[VibeBetter] Risk Report — PSRI: ${psri.toFixed(3)}`;

    if (opts.json) {
      const payload = {
        fields: {
          project: { key: opts.projectKey },
          summary,
          description,
          issuetype: { name: opts.issueType },
          priority: { name: priority },
          labels: ['vibebetter', 'risk-report'],
        },
      };
      console.log(JSON.stringify(payload, null, 2));
    } else {
      console.log(pc.bold('  Jira Ticket Preview\n'));
      console.log(`  ${pc.dim('Project:')}     ${opts.projectKey}`);
      console.log(`  ${pc.dim('Type:')}        ${opts.issueType}`);
      console.log(`  ${pc.dim('Priority:')}    ${priority}`);
      console.log(`  ${pc.dim('Summary:')}     ${summary}`);
      console.log();
      console.log(pc.bold('  Description:\n'));
      for (const line of description.split('\n')) {
        console.log(`  ${pc.dim(line)}`);
      }
      console.log();
      info('Use --json to get API-ready payload for Jira REST API');
    }
    console.log();
  });
