import { Command } from 'commander';
import pc from 'picocolors';
import { requireConfig } from '../config.js';
import { header, info } from '../utils/display.js';

function generateK8sManifest(projectId: string, image: string, replicas: number, namespace: string): string {
  return `# VibeBetter Kubernetes Deployment — generated by \`vibe k8s\`
# Project: ${projectId}

apiVersion: v1
kind: Namespace
metadata:
  name: ${namespace}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibebetter-server
  namespace: ${namespace}
  labels:
    app: vibebetter
    component: server
spec:
  replicas: ${replicas}
  selector:
    matchLabels:
      app: vibebetter
      component: server
  template:
    metadata:
      labels:
        app: vibebetter
        component: server
    spec:
      containers:
        - name: server
          image: ${image}
          ports:
            - containerPort: 3001
              name: http
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vibebetter-secrets
                  key: database-url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: vibebetter-secrets
                  key: redis-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: vibebetter-secrets
                  key: jwt-secret
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: vibebetter-server
  namespace: ${namespace}
spec:
  selector:
    app: vibebetter
    component: server
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  type: ClusterIP
`;
}

export const k8sCommand = new Command('k8s')
  .description('Generate Kubernetes deployment manifest for VibeBetter')
  .option('--image <image>', 'Container image', 'vibebetter/server:latest')
  .option('--replicas <n>', 'Number of replicas', '2')
  .option('--namespace <ns>', 'Kubernetes namespace', 'vibebetter')
  .option('--output <file>', 'Write to file instead of stdout')
  .action(async (opts) => {
    header('Kubernetes Manifest Generator');

    const config = requireConfig();
    const projectId = config.projectId ?? 'default';
    const manifest = generateK8sManifest(projectId, opts.image, parseInt(opts.replicas), opts.namespace);

    if (opts.output) {
      const fs = await import('node:fs');
      fs.writeFileSync(opts.output, manifest, 'utf-8');
      info(`Written to ${pc.bold(opts.output)}`);
    } else {
      console.log(manifest);
    }

    console.log();
    info('Apply with: kubectl apply -f <file>');
  });
