import { Command } from 'commander';
import pc from 'picocolors';
import { requireConfig } from '../config.js';
import { ApiClient } from '../api-client.js';
import { header, info, success } from '../utils/display.js';
import * as fs from 'node:fs';
import * as path from 'node:path';

function riskBadge(value: number): string {
  if (value <= 0.3) return '🟢 Low';
  if (value <= 0.6) return '🟡 Medium';
  return '🔴 High';
}

function buildMarkdown(
  overview: { psriScore: number | null; tdiScore: number | null; aiSuccessRate: number | null; totalPrs: number; hotspotFiles: number; totalFiles: number },
  hotspots: Array<{ filePath: string; riskScore: number; cyclomaticComplexity: number }>,
): string {
  const lines: string[] = [];
  const now = new Date().toISOString().slice(0, 10);
  const psri = overview.psriScore ?? 0;
  const tdi = overview.tdiScore ?? 0;
  const aiRate = overview.aiSuccessRate ?? 0;

  lines.push(`# VibeBetter Analysis Report`);
  lines.push('');
  lines.push(`**Generated:** ${now}  `);
  lines.push(`**Risk Level:** ${riskBadge(psri)}`);
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push('| Metric | Value | Status |');
  lines.push('|--------|-------|--------|');
  lines.push(`| PSRI Score | ${psri.toFixed(3)} | ${riskBadge(psri)} |`);
  lines.push(`| TDI Score | ${tdi.toFixed(3)} | ${riskBadge(tdi)} |`);
  lines.push(`| AI Success Rate | ${(aiRate * 100).toFixed(1)}% | ${aiRate >= 0.85 ? '🟢 Good' : aiRate >= 0.7 ? '🟡 Fair' : '🔴 Low'} |`);
  lines.push(`| Total PRs | ${overview.totalPrs} | — |`);
  lines.push(`| Total Files | ${overview.totalFiles} | — |`);
  lines.push(`| Hotspot Files | ${overview.hotspotFiles} | — |`);

  if (hotspots.length > 0) {
    lines.push('');
    lines.push('## Hotspot Files');
    lines.push('');
    lines.push('| # | File | Risk Score | Complexity |');
    lines.push('|---|------|-----------|------------|');
    for (let i = 0; i < Math.min(hotspots.length, 15); i++) {
      const h = hotspots[i]!;
      lines.push(`| ${i + 1} | \`${h.filePath}\` | ${Math.round(h.riskScore)} | ${h.cyclomaticComplexity} |`);
    }
  }

  lines.push('');
  lines.push('## Recommendations');
  lines.push('');
  if (psri > 0.6) lines.push('- ⚠️ **High risk** — prioritize refactoring hotspot files');
  if (tdi > 0.5) lines.push('- 🔧 **Tech debt** — schedule debt reduction sprints');
  if (aiRate < 0.7) lines.push('- 🤖 **AI effectiveness** — review AI tool configuration');
  if (psri <= 0.3 && tdi <= 0.3 && aiRate >= 0.85) lines.push('- ✅ All metrics look healthy!');
  lines.push('');
  lines.push('---');
  lines.push('*Generated by [VibeBetter CLI](https://vibebetter.dev)*');
  lines.push('');

  return lines.join('\n');
}

export const markdownReportCommand = new Command('markdown-report')
  .description('Generate full analysis as standalone markdown file')
  .option('-o, --output <file>', 'Output file path', 'vibebetter-report.md')
  .option('--stdout', 'Print to stdout instead of file')
  .action(async (opts) => {
    header('Markdown Report');
    const config = requireConfig();
    const client = new ApiClient(config);

    const overview = await client.getOverview().catch(() => null);
    if (!overview) {
      info('No metrics available. Run: vibe sync');
      return;
    }

    const hotspots = (await client.getTopFiles(15).catch(() => [])) || [];
    const markdown = buildMarkdown(overview, hotspots);

    if (opts.stdout) {
      console.log(markdown);
      return;
    }

    const filePath = path.resolve(process.cwd(), opts.output);
    fs.writeFileSync(filePath, markdown, 'utf-8');
    success(`Report written to ${filePath}`);
    console.log();
  });
