import { Command } from 'commander';
import pc from 'picocolors';
import { writeFileSync } from 'fs';
import { resolve } from 'path';
import { requireConfig } from '../config.js';
import { ApiClient } from '../api-client.js';
import { header, info } from '../utils/display.js';

interface NotebookCell {
  type: 'markdown' | 'code' | 'output';
  content: string;
}

function buildNotebook(projectName: string, metrics: Record<string, unknown>): NotebookCell[] {
  const cells: NotebookCell[] = [];

  cells.push({ type: 'markdown', content: `# VibeBetter Analysis — ${projectName}\n\n> Generated by \`vibe notebook\` on ${new Date().toISOString().split('T')[0]}` });
  cells.push({ type: 'markdown', content: '## Project Overview\n\nThis notebook contains the latest metrics and insights for your project.' });
  cells.push({ type: 'code', content: `project = "${projectName}"\nmetrics = ${JSON.stringify(metrics, null, 2)}` });
  cells.push({ type: 'output', content: `Loaded ${Object.keys(metrics).length} metric(s) for ${projectName}` });

  const psri = Number(metrics.psriScore ?? 0);
  const tdi = Number(metrics.tdiScore ?? 0);
  const hotspots = Number(metrics.hotspotFiles ?? 0);

  cells.push({ type: 'markdown', content: '## Risk Metrics' });
  cells.push({ type: 'code', content: `psri_score = ${psri.toFixed(3)}\ntdi_score = ${tdi.toFixed(3)}\nhotspot_count = ${hotspots}` });
  cells.push({ type: 'output', content: `PSRI: ${psri.toFixed(3)} | TDI: ${tdi.toFixed(3)} | Hotspots: ${hotspots}` });

  cells.push({ type: 'markdown', content: '## Interpretation\n\n' +
    `- **PSRI** ${psri <= 0.4 ? 'is healthy' : psri <= 0.6 ? 'needs attention' : 'is critical'} (${psri.toFixed(3)})\n` +
    `- **TDI** ${tdi <= 0.3 ? 'is low' : tdi <= 0.5 ? 'is moderate' : 'is high'} (${tdi.toFixed(3)})\n` +
    `- **Hotspots**: ${hotspots} file(s) flagged` });

  cells.push({ type: 'markdown', content: '---\n\n*Generated by VibeBetter CLI*' });
  return cells;
}

function renderMarkdown(cells: NotebookCell[]): string {
  return cells.map((cell) => {
    switch (cell.type) {
      case 'markdown': return cell.content;
      case 'code': return '```python\n' + cell.content + '\n```';
      case 'output': return '> **Output:** ' + cell.content;
      default: return cell.content;
    }
  }).join('\n\n');
}

export const notebookCommand = new Command('notebook')
  .description('Export analysis as Jupyter-style markdown notebook')
  .option('-o, --output <file>', 'Output file path', 'vibe-notebook.md')
  .option('--json', 'Output cells as JSON')
  .action(async (opts) => {
    header('VibeBetter Notebook');

    const config = requireConfig();
    const client = new ApiClient(config);

    const overview = await client.getOverview().catch(() => null);
    const projectName = config.projectId ?? 'project';
    const metrics = overview ?? { psriScore: 0, tdiScore: 0, hotspotFiles: 0 };

    const cells = buildNotebook(projectName, metrics as Record<string, unknown>);

    if (opts.json) {
      console.log(JSON.stringify(cells, null, 2));
      return;
    }

    const md = renderMarkdown(cells);
    const outPath = resolve(process.cwd(), opts.output);
    writeFileSync(outPath, md, 'utf-8');

    console.log(pc.green(`  \u2714 Notebook saved to ${outPath}`));
    console.log(pc.dim(`    ${cells.length} cells generated`));
    console.log();
    info('Open the .md file in VS Code or convert to .ipynb with jupytext');
  });
