import { Command } from 'commander';
import pc from 'picocolors';
import { requireConfig } from '../config.js';
import { header, info } from '../utils/display.js';

function generatePlaywrightTest(projectId: string, baseUrl: string, pages: string[]): string {
  const lines: string[] = [];

  lines.push('import { test, expect } from "@playwright/test";');
  lines.push('');
  lines.push(`// VibeBetter Dashboard E2E Tests — generated by \`vibe playwright\``);
  lines.push(`// Project: ${projectId}`);
  lines.push('');
  lines.push(`const BASE_URL = "${baseUrl}";`);
  lines.push('');
  lines.push('test.describe("VibeBetter Dashboard", () => {');

  if (pages.includes('dashboard')) {
    lines.push('  test("should load the dashboard overview", async ({ page }) => {');
    lines.push('    await page.goto(`${BASE_URL}/dashboard`);');
    lines.push('    await expect(page.locator("h1")).toContainText("Dashboard");');
    lines.push('    await expect(page.locator("[data-testid=\\"ai-success-rate\\"]")).toBeVisible();');
    lines.push('    await expect(page.locator("[data-testid=\\"psri-score\\"]")).toBeVisible();');
    lines.push('  });');
    lines.push('');
  }

  if (pages.includes('risk')) {
    lines.push('  test("should display risk trends chart", async ({ page }) => {');
    lines.push('    await page.goto(`${BASE_URL}/dashboard/risk`);');
    lines.push('    await expect(page.locator("[data-testid=\\"risk-chart\\"]")).toBeVisible();');
    lines.push('    await expect(page.locator("[data-testid=\\"hotspots-table\\"]")).toBeVisible();');
    lines.push('  });');
    lines.push('');
  }

  if (pages.includes('insights')) {
    lines.push('  test("should show AI insights", async ({ page }) => {');
    lines.push('    await page.goto(`${BASE_URL}/dashboard/insights`);');
    lines.push('    await expect(page.locator("[data-testid=\\"ai-insights\\"]")).toBeVisible();');
    lines.push('    await expect(page.locator("[data-testid=\\"tool-usage\\"]")).toBeVisible();');
    lines.push('  });');
    lines.push('');
  }

  if (pages.includes('settings')) {
    lines.push('  test("should update PSRI weights in settings", async ({ page }) => {');
    lines.push('    await page.goto(`${BASE_URL}/dashboard/settings`);');
    lines.push('    const slider = page.locator("[data-testid=\\"weight-structural\\"]");');
    lines.push('    await expect(slider).toBeVisible();');
    lines.push('  });');
    lines.push('');
  }

  lines.push('  test("should navigate between pages", async ({ page }) => {');
  lines.push('    await page.goto(`${BASE_URL}/dashboard`);');
  lines.push('    const nav = page.locator("nav");');
  lines.push('    await expect(nav).toBeVisible();');
  for (const p of pages) {
    lines.push(`    await page.click(\`nav a[href*="${p}"]\`);`);
    lines.push(`    await page.waitForURL(\`**/${p}*\`);`);
  }
  lines.push('  });');

  lines.push('});');

  return lines.join('\n');
}

export const playwrightCommand = new Command('playwright')
  .description('Generate Playwright E2E test for VibeBetter dashboard')
  .option('--base-url <url>', 'Base URL of the dashboard', 'http://localhost:3000')
  .option('--pages <pages>', 'Comma-separated pages to test', 'dashboard,risk,insights,settings')
  .option('--output <file>', 'Write to file instead of stdout')
  .action(async (opts) => {
    header('Playwright Test Generator');

    const config = requireConfig();
    const projectId = config.projectId ?? 'default';
    const pages = opts.pages.split(',').map((p: string) => p.trim());

    const testCode = generatePlaywrightTest(projectId, opts.baseUrl, pages);

    if (opts.output) {
      const fs = await import('node:fs');
      fs.writeFileSync(opts.output, testCode, 'utf-8');
      info(`Written to ${pc.bold(opts.output)}`);
    } else {
      console.log(testCode);
    }

    console.log();
    info('Run with: npx playwright test');
  });
