import { Command } from 'commander';
import pc from 'picocolors';
import { requireConfig } from '../config.js';
import { header, info } from '../utils/display.js';

function generatePulumiProgram(projectId: string, provider: string, region: string, tier: string): string {
  const lines: string[] = [];

  lines.push('import * as pulumi from "@pulumi/pulumi";');
  lines.push(`import * as ${provider} from "@pulumi/${provider}";`);
  lines.push('');
  lines.push(`// VibeBetter Infrastructure — generated by \`vibe pulumi\``);
  lines.push(`// Project: ${projectId} | Provider: ${provider} | Region: ${region}`);
  lines.push('');

  if (provider === 'aws') {
    lines.push('const vpc = new aws.ec2.Vpc("vibebetter-vpc", {');
    lines.push('  cidrBlock: "10.0.0.0/16",');
    lines.push('  enableDnsHostnames: true,');
    lines.push(`  tags: { Name: "vibebetter-${projectId}", Project: "${projectId}" },`);
    lines.push('});');
    lines.push('');
    lines.push('const subnet = new aws.ec2.Subnet("vibebetter-subnet", {');
    lines.push('  vpcId: vpc.id,');
    lines.push('  cidrBlock: "10.0.1.0/24",');
    lines.push(`  availabilityZone: "${region}a",`);
    lines.push('});');
    lines.push('');
    lines.push('const db = new aws.rds.Instance("vibebetter-db", {');
    lines.push(`  engine: "postgres",`);
    lines.push(`  engineVersion: "16",`);
    lines.push(`  instanceClass: "${tier === 'enterprise' ? 'db.r6g.xlarge' : 'db.t4g.medium'}",`);
    lines.push('  allocatedStorage: 50,');
    lines.push(`  dbName: "vibebetter",`);
    lines.push('  username: "vibebetter",');
    lines.push('  password: pulumi.secret("change-me"),');
    lines.push('  skipFinalSnapshot: true,');
    lines.push('});');
    lines.push('');
    lines.push('const redis = new aws.elasticache.Cluster("vibebetter-redis", {');
    lines.push('  engine: "redis",');
    lines.push(`  nodeType: "${tier === 'enterprise' ? 'cache.r6g.large' : 'cache.t4g.medium'}",`);
    lines.push('  numCacheNodes: 1,');
    lines.push('});');
    lines.push('');
    lines.push('const cluster = new aws.ecs.Cluster("vibebetter-cluster", {});');
    lines.push('');
    lines.push('export const vpcId = vpc.id;');
    lines.push('export const dbEndpoint = db.endpoint;');
    lines.push('export const redisEndpoint = redis.cacheNodes[0].address;');
  } else {
    lines.push(`const resourceGroup = new ${provider}.core.ResourceGroup("vibebetter-rg", {`);
    lines.push(`  location: "${region}",`);
    lines.push('});');
    lines.push('');
    lines.push(`const db = new ${provider}.postgresql.FlexibleServer("vibebetter-db", {`);
    lines.push('  resourceGroupName: resourceGroup.name,');
    lines.push('  location: resourceGroup.location,');
    lines.push(`  skuName: "${tier === 'enterprise' ? 'Standard_D4s_v3' : 'Standard_B2s'}",`);
    lines.push('  version: "16",');
    lines.push('  administratorLogin: "vibebetter",');
    lines.push('  administratorPassword: pulumi.secret("change-me"),');
    lines.push('});');
    lines.push('');
    lines.push('export const dbFqdn = db.fullyQualifiedDomainName;');
  }

  return lines.join('\n');
}

export const pulumiCommand = new Command('pulumi')
  .description('Generate Pulumi infrastructure code for VibeBetter deployment')
  .option('--provider <provider>', 'Cloud provider (aws, azure)', 'aws')
  .option('--region <region>', 'Cloud region', 'us-east-1')
  .option('--tier <tier>', 'Deployment tier (free, pro, enterprise)', 'pro')
  .option('--output <file>', 'Write to file instead of stdout')
  .action(async (opts) => {
    header('Pulumi Infrastructure Generator');

    const config = requireConfig();
    const projectId = config.projectId ?? 'default';

    const code = generatePulumiProgram(projectId, opts.provider, opts.region, opts.tier);

    if (opts.output) {
      const fs = await import('node:fs');
      fs.writeFileSync(opts.output, code, 'utf-8');
      info(`Written to ${pc.bold(opts.output)}`);
    } else {
      console.log(code);
    }

    console.log();
    info('Run with: pulumi up');
  });
