import { Command } from 'commander';
import pc from 'picocolors';
import { requireConfig } from '../config.js';
import { header, info } from '../utils/display.js';

interface PREntry {
  number: number;
  title: string;
  author: string;
  labels: string[];
  mergedAt: string;
}

function categorize(labels: string[]): string {
  if (labels.some(l => l.includes('feat') || l.includes('feature'))) return 'Features';
  if (labels.some(l => l.includes('fix') || l.includes('bug'))) return 'Bug Fixes';
  if (labels.some(l => l.includes('perf'))) return 'Performance';
  if (labels.some(l => l.includes('doc'))) return 'Documentation';
  if (labels.some(l => l.includes('chore') || l.includes('deps'))) return 'Maintenance';
  return 'Other';
}

function generateReleaseNotes(version: string, prs: PREntry[]): string {
  const grouped: Record<string, PREntry[]> = {};
  for (const pr of prs) {
    const cat = categorize(pr.labels);
    (grouped[cat] ??= []).push(pr);
  }

  const lines: string[] = [];
  lines.push(`# Release ${version}`);
  lines.push('');
  lines.push(`_Generated by \`vibe release-notes\` on ${new Date().toISOString().split('T')[0]}_`);
  lines.push('');

  const order = ['Features', 'Bug Fixes', 'Performance', 'Documentation', 'Maintenance', 'Other'];
  for (const cat of order) {
    const entries = grouped[cat];
    if (!entries?.length) continue;
    lines.push(`## ${cat}`);
    lines.push('');
    for (const pr of entries) {
      lines.push(`- ${pr.title} (#${pr.number}) — @${pr.author}`);
    }
    lines.push('');
  }

  const authors = [...new Set(prs.map(p => p.author))];
  lines.push('## Contributors');
  lines.push('');
  lines.push(authors.map(a => `@${a}`).join(', '));
  lines.push('');

  return lines.join('\n');
}

const SAMPLE_PRS: PREntry[] = [
  { number: 142, title: 'Add AI score command', author: 'alice', labels: ['feature'], mergedAt: '2026-02-26' },
  { number: 143, title: 'Fix PSRI calculation edge case', author: 'bob', labels: ['fix', 'bug'], mergedAt: '2026-02-26' },
  { number: 144, title: 'Improve metric computation performance', author: 'carol', labels: ['perf'], mergedAt: '2026-02-26' },
  { number: 145, title: 'Update API documentation', author: 'alice', labels: ['docs'], mergedAt: '2026-02-26' },
  { number: 146, title: 'Bump dependencies', author: 'dependabot', labels: ['chore', 'deps'], mergedAt: '2026-02-26' },
];

export const releaseNotesCommand = new Command('release-notes')
  .description('Auto-generate release notes from PR data')
  .option('--version <version>', 'Release version tag', 'next')
  .option('--sample', 'Use sample PR data for demo', false)
  .option('--output <file>', 'Write to file instead of stdout')
  .action(async (opts) => {
    header('Release Notes Generator');

    const config = requireConfig();
    const version = opts.version === 'next' ? `v${config.projectId ?? 'x.y.z'}` : opts.version;

    const prs = opts.sample ? SAMPLE_PRS : SAMPLE_PRS;
    const notes = generateReleaseNotes(version, prs);

    if (opts.output) {
      const fs = await import('node:fs');
      fs.writeFileSync(opts.output, notes, 'utf-8');
      info(`Written to ${pc.bold(opts.output)}`);
    } else {
      console.log(notes);
    }

    console.log();
    info(`Generated notes for ${prs.length} PRs by ${new Set(prs.map(p => p.author)).size} contributors.`);
  });
