import { Command } from 'commander';
import pc from 'picocolors';
import { requireConfig } from '../config.js';
import { ApiClient } from '../api-client.js';
import { header, info, success, error } from '../utils/display.js';

interface SlackBlock {
  type: string;
  text?: { type: string; text: string; emoji?: boolean };
  fields?: Array<{ type: string; text: string }>;
  elements?: Array<{ type: string; text: string }>;
}

function buildSlackPayload(overview: {
  psriScore: number | null;
  tdiScore: number | null;
  aiSuccessRate: number | null;
  totalPrs: number;
  hotspotFiles: number;
}): { blocks: SlackBlock[] } {
  const psri = overview.psriScore?.toFixed(3) ?? 'N/A';
  const tdi = overview.tdiScore?.toFixed(3) ?? 'N/A';
  const aiRate = overview.aiSuccessRate ? `${(overview.aiSuccessRate * 100).toFixed(1)}%` : 'N/A';
  const riskEmoji = (overview.psriScore ?? 0) <= 0.3 ? ':large_green_circle:' : (overview.psriScore ?? 0) <= 0.6 ? ':large_yellow_circle:' : ':red_circle:';

  return {
    blocks: [
      { type: 'header', text: { type: 'plain_text', text: ':bar_chart: VibeBetter Report', emoji: true } },
      { type: 'section', fields: [
        { type: 'mrkdwn', text: `*PSRI Score:*\n${riskEmoji} ${psri}` },
        { type: 'mrkdwn', text: `*TDI Score:*\n${tdi}` },
        { type: 'mrkdwn', text: `*AI Success:*\n${aiRate}` },
        { type: 'mrkdwn', text: `*Hotspots:*\n${overview.hotspotFiles} files` },
      ]},
      { type: 'context', elements: [{ type: 'mrkdwn', text: `Total PRs: ${overview.totalPrs} | Generated by VibeBetter CLI` }] },
    ],
  };
}

export const slackReportCommand = new Command('slack-report')
  .description('Format report for Slack webhook posting')
  .option('--webhook <url>', 'Slack webhook URL')
  .option('--dry-run', 'Print payload without sending')
  .action(async (opts) => {
    header('Slack Report');
    const config = requireConfig();
    const client = new ApiClient(config);

    const overview = await client.getOverview().catch(() => null);
    if (!overview) {
      info('No metrics available. Run: vibe sync');
      return;
    }

    const payload = buildSlackPayload(overview);

    if (opts.dryRun || !opts.webhook) {
      console.log(pc.bold('  Slack Payload (JSON):\n'));
      console.log(JSON.stringify(payload, null, 2));
      if (!opts.webhook) {
        console.log();
        info('Use --webhook <url> to post directly, or --dry-run to preview.');
      }
      console.log();
      return;
    }

    try {
      const res = await fetch(opts.webhook, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      if (res.ok) success('Report posted to Slack');
      else error(`Slack responded with ${res.status}`);
    } catch {
      error('Failed to reach Slack webhook');
    }
    console.log();
  });
