import { Command } from 'commander';
import pc from 'picocolors';
import { requireConfig } from '../config.js';
import { header, info } from '../utils/display.js';

function generateTerraform(projectId: string, region: string, tier: string): string {
  const lines: string[] = [];

  lines.push('# VibeBetter Infrastructure — generated by `vibe terraform`');
  lines.push(`# Project: ${projectId}`);
  lines.push(`# Region: ${region}`);
  lines.push(`# Tier: ${tier}`);
  lines.push('');
  lines.push('terraform {');
  lines.push('  required_version = ">= 1.5.0"');
  lines.push('  required_providers {');
  lines.push('    aws = { source = "hashicorp/aws", version = "~> 5.0" }');
  lines.push('  }');
  lines.push('}');
  lines.push('');
  lines.push(`provider "aws" { region = "${region}" }`);
  lines.push('');
  lines.push('# --- Database ---');
  lines.push('resource "aws_db_instance" "vibebetter" {');
  lines.push(`  identifier     = "vibebetter-${projectId}"`)
  lines.push(`  engine         = "postgres"`);
  lines.push(`  engine_version = "16.2"`);
  lines.push(`  instance_class = "${tier === 'enterprise' ? 'db.r6g.xlarge' : 'db.t4g.medium'}"`);
  lines.push('  allocated_storage = 50');
  lines.push('  storage_encrypted = true');
  lines.push(`  db_name  = "vibebetter"`);
  lines.push(`  username = "vibebetter"`);
  lines.push('  manage_master_user_password = true');
  lines.push('  skip_final_snapshot = false');
  lines.push(`  final_snapshot_identifier = "vibebetter-${projectId}-final"`);
  lines.push('}');
  lines.push('');
  lines.push('# --- Redis ---');
  lines.push('resource "aws_elasticache_replication_group" "vibebetter" {');
  lines.push(`  replication_group_id = "vibebetter-${projectId}"`);
  lines.push('  description         = "VibeBetter cache"');
  lines.push(`  node_type           = "${tier === 'enterprise' ? 'cache.r6g.large' : 'cache.t4g.medium'}"`);
  lines.push('  num_cache_clusters  = 2');
  lines.push('  engine              = "redis"');
  lines.push('  engine_version      = "7.1"');
  lines.push('  at_rest_encryption_enabled = true');
  lines.push('  transit_encryption_enabled = true');
  lines.push('}');
  lines.push('');
  lines.push('# --- ECS Service ---');
  lines.push('resource "aws_ecs_service" "vibebetter_api" {');
  lines.push(`  name            = "vibebetter-api"`);
  lines.push('  cluster         = aws_ecs_cluster.vibebetter.id');
  lines.push(`  desired_count   = ${tier === 'enterprise' ? 3 : 1}`);
  lines.push('  launch_type     = "FARGATE"');
  lines.push('}');
  lines.push('');
  lines.push('resource "aws_ecs_cluster" "vibebetter" {');
  lines.push(`  name = "vibebetter-${projectId}"`);
  lines.push('}');

  return lines.join('\n');
}

export const terraformCommand = new Command('terraform')
  .description('Generate Terraform config for VibeBetter infrastructure')
  .option('--region <region>', 'AWS region', 'us-east-1')
  .option('--tier <tier>', 'Deployment tier (free, pro, enterprise)', 'pro')
  .option('--output <file>', 'Write to file instead of stdout')
  .action(async (opts) => {
    header('Terraform Config');

    const config = requireConfig();
    const projectId = config.projectId ?? 'default';
    const tf = generateTerraform(projectId, opts.region, opts.tier);

    if (opts.output) {
      const fs = await import('node:fs');
      fs.writeFileSync(opts.output, tf, 'utf-8');
      info(`Written to ${pc.bold(opts.output)}`);
    } else {
      console.log(tf);
    }

    console.log();
    info('Review and customize before applying: terraform plan');
  });
