export const AI_LABELS = ['ai-generated', 'ai-assisted', 'copilot', 'cursor', 'ai-coded'];

export const AI_COMMIT_KEYWORDS = [
  'generated by ai',
  'ai-generated',
  'copilot',
  'cursor',
  'ai assisted',
  'llm generated',
];

export const PSRI_DEFAULT_WEIGHTS = {
  structural: 0.25,
  change: 0.25,
  defect: 0.25,
  coverage: 0.25,
} as const;

export const HOTSPOT_THRESHOLDS = {
  minChangeFrequency: 5,
  minComplexity: 15,
} as const;

export const COLLECTION_INTERVALS = {
  DAILY: 24 * 60 * 60 * 1000,
  HOURLY: 60 * 60 * 1000,
} as const;
