export const AI_LABELS = ['ai-generated', 'ai-assisted', 'copilot', 'cursor', 'ai-coded'];

export const AI_COMMIT_KEYWORDS = [
  'generated by ai',
  'ai-generated',
  'copilot',
  'cursor',
  'ai assisted',
  'llm generated',
];

export const PSRI_DEFAULT_WEIGHTS = {
  structural: 0.2,
  change: 0.2,
  defect: 0.2,
  architecture: 0.15,
  runtime: 0.1,
  coverage: 0.15,
} as const;

export const HOTSPOT_THRESHOLDS = {
  minChangeFrequency: 5,
  minComplexity: 15,
} as const;

export const COLLECTION_INTERVALS = {
  DAILY: 24 * 60 * 60 * 1000,
  HOURLY: 60 * 60 * 1000,
} as const;

export { INDUSTRY_BENCHMARKS, getBenchmarkLevel } from './benchmarks';
export { BRANDING } from './branding';
export { PRICING_TIERS } from './pricing';
export type { PricingTier } from './pricing';
export { INTEGRATIONS, getIntegration, getIntegrationsByCategory } from './integrations';
export type { Integration } from './integrations';
