import { describe, it, expect } from 'vitest';

describe('API Integration', () => {
  describe('Auth flow', () => {
    it('should register a new user', async () => {
      const { RegisterSchema } = await import('@vibebetter/shared');
      const valid = RegisterSchema.safeParse({ email: 'test@test.com', name: 'Test', password: '12345678' });
      expect(valid.success).toBe(true);
    });

    it('should reject invalid registration', async () => {
      const { RegisterSchema } = await import('@vibebetter/shared');
      const invalid = RegisterSchema.safeParse({ email: 'bad', name: '', password: '123' });
      expect(invalid.success).toBe(false);
    });

    it('should reject invalid login', async () => {
      const { LoginSchema } = await import('@vibebetter/shared');
      const invalid = LoginSchema.safeParse({ email: 'bad', password: '' });
      expect(invalid.success).toBe(false);
    });
  });

  describe('Project validation', () => {
    it('should validate project creation input', async () => {
      const { CreateProjectSchema } = await import('@vibebetter/shared');
      const valid = CreateProjectSchema.safeParse({ name: 'Test', repoUrl: 'https://github.com/org/repo' });
      expect(valid.success).toBe(true);
    });

    it('should reject invalid repo URL', async () => {
      const { CreateProjectSchema } = await import('@vibebetter/shared');
      const invalid = CreateProjectSchema.safeParse({ name: 'Test', repoUrl: 'not-a-url' });
      expect(invalid.success).toBe(false);
    });
  });

  describe('Weight validation', () => {
    it('should validate weight config', async () => {
      const { WeightConfigSchema } = await import('@vibebetter/shared');
      const valid = WeightConfigSchema.safeParse({
        structural: 0.2,
        change: 0.2,
        defect: 0.2,
        architecture: 0.15,
        runtime: 0.1,
        coverage: 0.15,
      });
      expect(valid.success).toBe(true);
    });

    it('should reject weights > 1', async () => {
      const { WeightConfigSchema } = await import('@vibebetter/shared');
      const invalid = WeightConfigSchema.safeParse({
        structural: 1.5,
        change: 0.2,
        defect: 0.2,
        architecture: 0.15,
        runtime: 0.1,
        coverage: 0.15,
      });
      expect(invalid.success).toBe(false);
    });
  });

  describe('Behavior validation', () => {
    it('should validate AI behavior input', async () => {
      const { AiBehaviorSchema } = await import('@vibebetter/shared');
      const valid = AiBehaviorSchema.safeParse({ tool: 'cursor', action: 'code_gen', generationCount: 5 });
      expect(valid.success).toBe(true);
    });

    it('should validate user behavior input', async () => {
      const { UserBehaviorSchema } = await import('@vibebetter/shared');
      const valid = UserBehaviorSchema.safeParse({ eventType: 'file_edit', sessionDuration: 3600 });
      expect(valid.success).toBe(true);
    });
  });
});

describe('MetricsService Logic', () => {
  it('safeDiv handles edge cases', async () => {
    const { safeDiv } = await import('@vibebetter/shared');
    expect(safeDiv(10, 0)).toBeNull();
    expect(safeDiv(0, 10)).toBe(0);
    expect(safeDiv(10, 5)).toBe(2);
    expect(safeDiv(1, 3)).toBeCloseTo(0.333, 2);
  });

  it('isAiPr detects AI labels', async () => {
    const { isAiPr } = await import('@vibebetter/shared');
    expect(isAiPr(['ai-generated'], [])).toBe(true);
    expect(isAiPr(['bug-fix'], [])).toBe(false);
    expect(isAiPr([], ['Generated by AI assistant'])).toBe(true);
    expect(isAiPr([], ['normal commit message'])).toBe(false);
    expect(isAiPr(['copilot-assisted'], ['fix: bug'])).toBe(true);
  });

  it('formatDate formats correctly', async () => {
    const { formatDate } = await import('@vibebetter/shared');
    expect(formatDate(new Date('2026-01-15T00:00:00Z'))).toBe('2026-01-15');
  });

  it('clamp constrains values', async () => {
    const { clamp } = await import('@vibebetter/shared');
    expect(clamp(5, 0, 10)).toBe(5);
    expect(clamp(-5, 0, 10)).toBe(0);
    expect(clamp(15, 0, 10)).toBe(10);
    expect(clamp(0, 0, 0)).toBe(0);
  });

  it('toPercent formats percentages', async () => {
    const { toPercent } = await import('@vibebetter/shared');
    expect(toPercent(0.856)).toBe('85.6%');
    expect(toPercent(0)).toBe('0.0%');
    expect(toPercent(1)).toBe('100.0%');
    expect(toPercent(null)).toBe('N/A');
  });
});

describe('Constants', () => {
  it('PSRI default weights sum to ~1', async () => {
    const { PSRI_DEFAULT_WEIGHTS } = await import('@vibebetter/shared');
    const sum = Object.values(PSRI_DEFAULT_WEIGHTS).reduce((a, b) => a + b, 0);
    expect(sum).toBeCloseTo(1, 1);
  });

  it('HOTSPOT_THRESHOLDS are positive', async () => {
    const { HOTSPOT_THRESHOLDS } = await import('@vibebetter/shared');
    expect(HOTSPOT_THRESHOLDS.minChangeFrequency).toBeGreaterThan(0);
    expect(HOTSPOT_THRESHOLDS.minComplexity).toBeGreaterThan(0);
  });
});
