#!/usr/bin/env node
import { Command } from 'commander';
import { initCommand } from './commands/init.js';
import { statusCommand } from './commands/status.js';
import { checkCommand } from './commands/check.js';
import { riskCommand } from './commands/risk.js';
import { decisionsCommand } from './commands/decisions.js';
import { insightsCommand } from './commands/insights.js';
import { reportCommand } from './commands/report.js';
import { syncCommand } from './commands/sync.js';
import { analyzeCommand } from './commands/analyze.js';
import { digestCommand } from './commands/digest.js';
import { fixCommand } from './commands/fix.js';
import { prRiskCommand } from './commands/pr-risk.js';
import { diffCommand } from './commands/diff.js';
import { dashboardCommand } from './commands/dashboard.js';
import { healthCommand } from './commands/health.js';
import { changelogCommand } from './commands/changelog.js';
import { reviewCommand } from './commands/review.js';
import { ciCommand } from './commands/ci.js';
import { watchCommand } from './commands/watch.js';
import { configCommand } from './commands/config-cmd.js';
import { hookCommand } from './commands/hook.js';
import { searchCommand } from './commands/search.js';
import { explainCommand } from './commands/explain.js';
import { badgeCommand } from './commands/badge.js';
import { summaryCommand } from './commands/summary.js';
import { historyCommand } from './commands/history.js';
import { exportConfigCommand } from './commands/export-config.js';
import { trendsCommand } from './commands/trends.js';
import { helpMeCommand } from './commands/help-me.js';
import { deployCheckCommand } from './commands/deploy-check.js';
import { compareToolsCommand } from './commands/compare-tools.js';
import { onboardCommand } from './commands/onboard.js';
import { slackReportCommand } from './commands/slack-report.js';
import { hotspotsCommand } from './commands/hotspots.js';
import { whatIfCommand } from './commands/what-if.js';
import { gitStatsCommand } from './commands/git-stats.js';
import { topCommand } from './commands/top.js';
import { whyCommand } from './commands/why.js';
import { jiraCommand } from './commands/jira.js';
import { profileCommand } from './commands/profile.js';
import { ignoreCommand } from './commands/ignore.js';
import { gitlabCommand } from './commands/gitlab.js';
import { scorecardCommand } from './commands/scorecard.js';
import { suggestCommand } from './commands/suggest.js';
import { githubActionCommand } from './commands/github-action.js';
import { leaderboardCommand } from './commands/leaderboard.js';
import { setupHooksCommand } from './commands/setup-hooks.js';
import { dockerCommand } from './commands/docker.js';
import { forecastCommand } from './commands/forecast.js';
import { quickCommand } from './commands/quick.js';
import { markdownReportCommand } from './commands/markdown-report.js';
import { sprintPlanCommand } from './commands/sprint-plan.js';
import { annotateCommand } from './commands/annotate.js';
import { preReviewCommand } from './commands/pre-review.js';
import { goalsCommand } from './commands/goals.js';
import { aliasCommand } from './commands/alias.js';
import { standupCommand } from './commands/standup.js';
import { versionInfoCommand } from './commands/version-info.js';
import { interactiveCommand } from './commands/interactive.js';
import { retroCommand } from './commands/retro.js';
import { benchmarkCommand } from './commands/benchmark.js';
import { notifyCommand } from './commands/notify.js';
import { complianceCommand } from './commands/compliance.js';
import { flowCommand } from './commands/flow.js';
import { tutorialCommand } from './commands/tutorial.js';
import { gitlabCiCommand } from './commands/gitlab-ci.js';
import { modulesCommand } from './commands/modules.js';
import { pinCommand } from './commands/pin.js';
import { preMergeCommand } from './commands/pre-merge.js';
import { timelineCommand } from './commands/timeline.js';
import { focusCommand } from './commands/focus.js';
import { bitbucketCommand } from './commands/bitbucket.js';
import { contributorsCommand } from './commands/contributors.js';
import { preferencesCommand } from './commands/preferences.js';
import { azureCommand } from './commands/azure.js';
import { doctorCommand } from './commands/doctor.js';
import { notebookCommand } from './commands/notebook.js';
import { feedbackCommand } from './commands/feedback.js';
import { sonarqubeCommand } from './commands/sonarqube.js';
import { shortcutsCommand } from './commands/shortcuts.js';
import { datadogCommand } from './commands/datadog.js';
import { resetCommand } from './commands/reset.js';
import { prometheusCommand } from './commands/prometheus.js';
import { improveCommand } from './commands/improve.js';
import { terraformCommand } from './commands/terraform.js';
import { compareBranchesCommand } from './commands/compare-branches.js';
import { emailReportCommand } from './commands/email-report.js';
import { cleanCommand } from './commands/clean.js';
import { csvCommand } from './commands/csv.js';
import { undoCommand } from './commands/undo.js';
import { opentelemetryCommand } from './commands/opentelemetry.js';
import { diffFilesCommand } from './commands/diff-files.js';
import { bookmarksCommand } from './commands/bookmarks.js';
import { jenkinsCommand } from './commands/jenkins.js';
import { depsCommand } from './commands/deps.js';
import { remindCommand } from './commands/remind.js';
import { k8sCommand } from './commands/k8s.js';
import { coverageCommand } from './commands/coverage.js';
import { journalCommand } from './commands/journal.js';
import { backstageCommand } from './commands/backstage.js';
import { velocityCommand } from './commands/velocity.js';
import { cheatsheetCommand } from './commands/cheatsheet.js';
import { argocdCommand } from './commands/argocd.js';
import { graphCommand } from './commands/graph.js';
import { calmCommand } from './commands/calm.js';
import { vercelCommand } from './commands/vercel.js';
import { matrixCommand } from './commands/matrix.js';
import { autofixCommand } from './commands/autofix.js';
import { helmCommand } from './commands/helm.js';
import { studioCommand } from './commands/studio.js';
import { askCommand } from './commands/ask.js';
import { composeCommand } from './commands/compose.js';
import { dashboardUrlCommand } from './commands/dashboard-url.js';
import { offlineCommand } from './commands/offline.js';
import { ansibleCommand } from './commands/ansible.js';
import { aiScoreCommand } from './commands/ai-score.js';
import { walkthroughCommand } from './commands/walkthrough.js';
import { pulumiCommand } from './commands/pulumi.js';
import { radarCommand } from './commands/radar.js';
import { faqCommand } from './commands/faq.js';
import { chromaticCommand } from './commands/chromatic.js';
import { predictCommand } from './commands/predict.js';
import { demoCommand } from './commands/demo.js';
import { playwrightCommand } from './commands/playwright.js';
import { releaseNotesCommand } from './commands/release-notes.js';
import { celebrateCommand } from './commands/celebrate.js';
import { ecosystemCommand } from './commands/ecosystem.js';
import { pulseCommand } from './commands/pulse.js';
import { learnCommand } from './commands/learn.js';
import { monorepoCommand } from './commands/monorepo.js';
import { impactCommand } from './commands/impact.js';
import { langCommand } from './commands/lang.js';
import { npmPublishCommand } from './commands/npm-publish.js';
import { roadmapCommand } from './commands/roadmap.js';
import { discordCommand } from './commands/discord.js';
import { smartReviewCommand } from './commands/smart-review.js';
import { wellbeingCommand } from './commands/wellbeing.js';
import { teamHealthCommand } from './commands/team-health.js';
import { aiRoiCommand } from './commands/ai-roi.js';
import { pairSuggestCommand } from './commands/pair-suggest.js';
import { techRadarCommand } from './commands/tech-radar.js';
import { codeOwnersCommand } from './commands/code-owners.js';
import { burndownCommand } from './commands/burndown.js';
import { adoptionCommand } from './commands/adoption.js';
import { mentorCommand } from './commands/mentor.js';
import { complexityTrendCommand } from './commands/complexity-trend.js';
import { releaseRiskCommand } from './commands/release-risk.js';
import { knowledgeMapCommand } from './commands/knowledge-map.js';
import { sprintReviewCommand } from './commands/sprint-review.js';
import { debtBudgetCommand } from './commands/debt-budget.js';
import { refactorPlanCommand } from './commands/refactor-plan.js';
import { testCoverageMapCommand } from './commands/test-coverage-map.js';
import { apiHealthCommand } from './commands/api-health.js';
import { securityScanCommand } from './commands/security-scan.js';
import { onboardDevCommand } from './commands/onboard-dev.js';
import { architectureCheckCommand } from './commands/architecture-check.js';
import { performanceBudgetCliCommand } from './commands/performance-budget-cli.js';
import { dependencyGraphCommand } from './commands/dependency-graph.js';
import { moduleRiskCommand } from './commands/module-risk.js';
import { teamVelocityCommand } from './commands/team-velocity.js';
import { codeChurnCommand } from './commands/code-churn.js';
import { commitQualityCommand } from './commands/commit-quality.js';
import { reviewEfficiencyCommand } from './commands/review-efficiency.js';
import { aiAccuracyCommand } from './commands/ai-accuracy.js';
import { skillMatrixCommand } from './commands/skill-matrix.js';
import { incidentRiskCommand } from './commands/incident-risk.js';
import { capacityPlanCommand } from './commands/capacity-plan.js';
import { governanceCommand } from './commands/governance.js';
import { techDebtRoiCommand } from './commands/tech-debt-roi.js';
import { aiSafetyCommand } from './commands/ai-safety.js';
import { migrationPlanCommand } from './commands/migration-plan.js';
import { busFactorCommand } from './commands/bus-factor.js';
import { qualityGateCommand } from './commands/quality-gate.js';
import { changelogGenCommand } from './commands/changelog-gen.js';
import { deprecationCommand } from './commands/deprecation.js';
import { cognitiveLoadCommand } from './commands/cognitive-load.js';
import { sustainabilityCommand } from './commands/sustainability.js';

const program = new Command();
program
  .name('vibe')
  .description('VibeBetter CLI — AI Coding Insight in your terminal')
  .version('3.8.0');

program.addCommand(initCommand);
program.addCommand(statusCommand);
program.addCommand(checkCommand);
program.addCommand(riskCommand);
program.addCommand(decisionsCommand);
program.addCommand(insightsCommand);
program.addCommand(reportCommand);
program.addCommand(syncCommand);
program.addCommand(analyzeCommand);
program.addCommand(digestCommand);
program.addCommand(fixCommand);
program.addCommand(prRiskCommand);
program.addCommand(diffCommand);
program.addCommand(dashboardCommand);
program.addCommand(healthCommand);
program.addCommand(changelogCommand);
program.addCommand(reviewCommand);
program.addCommand(ciCommand);
program.addCommand(watchCommand);
program.addCommand(configCommand);
program.addCommand(hookCommand);
program.addCommand(searchCommand);
program.addCommand(explainCommand);
program.addCommand(badgeCommand);
program.addCommand(summaryCommand);
program.addCommand(historyCommand);
program.addCommand(exportConfigCommand);
program.addCommand(trendsCommand);
program.addCommand(helpMeCommand);
program.addCommand(deployCheckCommand);
program.addCommand(compareToolsCommand);
program.addCommand(onboardCommand);
program.addCommand(slackReportCommand);
program.addCommand(hotspotsCommand);
program.addCommand(whatIfCommand);
program.addCommand(gitStatsCommand);
program.addCommand(topCommand);
program.addCommand(whyCommand);
program.addCommand(jiraCommand);
program.addCommand(profileCommand);
program.addCommand(ignoreCommand);
program.addCommand(gitlabCommand);
program.addCommand(scorecardCommand);
program.addCommand(suggestCommand);
program.addCommand(githubActionCommand);
program.addCommand(leaderboardCommand);
program.addCommand(setupHooksCommand);
program.addCommand(dockerCommand);
program.addCommand(forecastCommand);
program.addCommand(quickCommand);
program.addCommand(markdownReportCommand);
program.addCommand(sprintPlanCommand);
program.addCommand(annotateCommand);
program.addCommand(preReviewCommand);
program.addCommand(goalsCommand);
program.addCommand(aliasCommand);
program.addCommand(standupCommand);
program.addCommand(versionInfoCommand);
program.addCommand(interactiveCommand);
program.addCommand(retroCommand);
program.addCommand(benchmarkCommand);
program.addCommand(notifyCommand);
program.addCommand(complianceCommand);
program.addCommand(flowCommand);
program.addCommand(tutorialCommand);
program.addCommand(gitlabCiCommand);
program.addCommand(modulesCommand);
program.addCommand(pinCommand);
program.addCommand(preMergeCommand);
program.addCommand(timelineCommand);
program.addCommand(focusCommand);
program.addCommand(bitbucketCommand);
program.addCommand(contributorsCommand);
program.addCommand(preferencesCommand);
program.addCommand(azureCommand);
program.addCommand(doctorCommand);
program.addCommand(notebookCommand);
program.addCommand(feedbackCommand);
program.addCommand(sonarqubeCommand);
program.addCommand(shortcutsCommand);
program.addCommand(datadogCommand);
program.addCommand(resetCommand);
program.addCommand(prometheusCommand);
program.addCommand(improveCommand);
program.addCommand(terraformCommand);
program.addCommand(compareBranchesCommand);
program.addCommand(emailReportCommand);
program.addCommand(cleanCommand);
program.addCommand(csvCommand);
program.addCommand(undoCommand);
program.addCommand(opentelemetryCommand);
program.addCommand(diffFilesCommand);
program.addCommand(bookmarksCommand);
program.addCommand(jenkinsCommand);
program.addCommand(depsCommand);
program.addCommand(remindCommand);
program.addCommand(k8sCommand);
program.addCommand(coverageCommand);
program.addCommand(journalCommand);
program.addCommand(backstageCommand);
program.addCommand(velocityCommand);
program.addCommand(cheatsheetCommand);
program.addCommand(argocdCommand);
program.addCommand(graphCommand);
program.addCommand(calmCommand);
program.addCommand(vercelCommand);
program.addCommand(matrixCommand);
program.addCommand(autofixCommand);
program.addCommand(helmCommand);
program.addCommand(studioCommand);
program.addCommand(askCommand);
program.addCommand(composeCommand);
program.addCommand(dashboardUrlCommand);
program.addCommand(offlineCommand);
program.addCommand(ansibleCommand);
program.addCommand(aiScoreCommand);
program.addCommand(walkthroughCommand);
program.addCommand(pulumiCommand);
program.addCommand(radarCommand);
program.addCommand(faqCommand);
program.addCommand(chromaticCommand);
program.addCommand(predictCommand);
program.addCommand(demoCommand);
program.addCommand(playwrightCommand);
program.addCommand(releaseNotesCommand);
program.addCommand(celebrateCommand);
program.addCommand(ecosystemCommand);
program.addCommand(pulseCommand);
program.addCommand(learnCommand);
program.addCommand(monorepoCommand);
program.addCommand(impactCommand);
program.addCommand(langCommand);
program.addCommand(npmPublishCommand);
program.addCommand(roadmapCommand);
program.addCommand(discordCommand);
program.addCommand(smartReviewCommand);
program.addCommand(wellbeingCommand);
program.addCommand(teamHealthCommand);
program.addCommand(aiRoiCommand);
program.addCommand(pairSuggestCommand);
program.addCommand(techRadarCommand);
program.addCommand(codeOwnersCommand);
program.addCommand(burndownCommand);
program.addCommand(adoptionCommand);
program.addCommand(mentorCommand);
program.addCommand(complexityTrendCommand);
program.addCommand(releaseRiskCommand);
program.addCommand(knowledgeMapCommand);
program.addCommand(sprintReviewCommand);
program.addCommand(debtBudgetCommand);
program.addCommand(refactorPlanCommand);
program.addCommand(testCoverageMapCommand);
program.addCommand(apiHealthCommand);
program.addCommand(securityScanCommand);
program.addCommand(onboardDevCommand);
program.addCommand(architectureCheckCommand);
program.addCommand(performanceBudgetCliCommand);
program.addCommand(dependencyGraphCommand);
program.addCommand(moduleRiskCommand);
program.addCommand(teamVelocityCommand);
program.addCommand(codeChurnCommand);
program.addCommand(commitQualityCommand);
program.addCommand(reviewEfficiencyCommand);
program.addCommand(aiAccuracyCommand);
program.addCommand(skillMatrixCommand);
program.addCommand(incidentRiskCommand);
program.addCommand(capacityPlanCommand);
program.addCommand(governanceCommand);
program.addCommand(techDebtRoiCommand);
program.addCommand(aiSafetyCommand);
program.addCommand(migrationPlanCommand);
program.addCommand(busFactorCommand);
program.addCommand(qualityGateCommand);
program.addCommand(changelogGenCommand);
program.addCommand(deprecationCommand);
program.addCommand(cognitiveLoadCommand);
program.addCommand(sustainabilityCommand);

program.parse();
