#!/usr/bin/env node
import { Command } from 'commander';
import { initCommand } from './commands/init.js';
import { statusCommand } from './commands/status.js';
import { checkCommand } from './commands/check.js';
import { riskCommand } from './commands/risk.js';
import { decisionsCommand } from './commands/decisions.js';
import { insightsCommand } from './commands/insights.js';
import { reportCommand } from './commands/report.js';
import { syncCommand } from './commands/sync.js';
import { analyzeCommand } from './commands/analyze.js';
import { digestCommand } from './commands/digest.js';
import { fixCommand } from './commands/fix.js';
import { prRiskCommand } from './commands/pr-risk.js';
import { diffCommand } from './commands/diff.js';
import { dashboardCommand } from './commands/dashboard.js';
import { healthCommand } from './commands/health.js';
import { changelogCommand } from './commands/changelog.js';
import { reviewCommand } from './commands/review.js';
import { ciCommand } from './commands/ci.js';
import { watchCommand } from './commands/watch.js';
import { configCommand } from './commands/config-cmd.js';
import { hookCommand } from './commands/hook.js';
import { searchCommand } from './commands/search.js';
import { explainCommand } from './commands/explain.js';
import { badgeCommand } from './commands/badge.js';
import { summaryCommand } from './commands/summary.js';
import { historyCommand } from './commands/history.js';
import { exportConfigCommand } from './commands/export-config.js';
import { trendsCommand } from './commands/trends.js';
import { helpMeCommand } from './commands/help-me.js';
import { deployCheckCommand } from './commands/deploy-check.js';
import { compareToolsCommand } from './commands/compare-tools.js';
import { onboardCommand } from './commands/onboard.js';
import { slackReportCommand } from './commands/slack-report.js';
import { hotspotsCommand } from './commands/hotspots.js';
import { whatIfCommand } from './commands/what-if.js';
import { gitStatsCommand } from './commands/git-stats.js';
import { topCommand } from './commands/top.js';
import { whyCommand } from './commands/why.js';
import { jiraCommand } from './commands/jira.js';
import { profileCommand } from './commands/profile.js';
import { ignoreCommand } from './commands/ignore.js';
import { gitlabCommand } from './commands/gitlab.js';
import { scorecardCommand } from './commands/scorecard.js';
import { suggestCommand } from './commands/suggest.js';
import { githubActionCommand } from './commands/github-action.js';
import { leaderboardCommand } from './commands/leaderboard.js';
import { setupHooksCommand } from './commands/setup-hooks.js';
import { dockerCommand } from './commands/docker.js';
import { forecastCommand } from './commands/forecast.js';
import { quickCommand } from './commands/quick.js';
import { markdownReportCommand } from './commands/markdown-report.js';

const program = new Command();
program
  .name('vibe')
  .description('VibeBetter CLI — AI Coding Insight in your terminal')
  .version('0.88.0');

program.addCommand(initCommand);
program.addCommand(statusCommand);
program.addCommand(checkCommand);
program.addCommand(riskCommand);
program.addCommand(decisionsCommand);
program.addCommand(insightsCommand);
program.addCommand(reportCommand);
program.addCommand(syncCommand);
program.addCommand(analyzeCommand);
program.addCommand(digestCommand);
program.addCommand(fixCommand);
program.addCommand(prRiskCommand);
program.addCommand(diffCommand);
program.addCommand(dashboardCommand);
program.addCommand(healthCommand);
program.addCommand(changelogCommand);
program.addCommand(reviewCommand);
program.addCommand(ciCommand);
program.addCommand(watchCommand);
program.addCommand(configCommand);
program.addCommand(hookCommand);
program.addCommand(searchCommand);
program.addCommand(explainCommand);
program.addCommand(badgeCommand);
program.addCommand(summaryCommand);
program.addCommand(historyCommand);
program.addCommand(exportConfigCommand);
program.addCommand(trendsCommand);
program.addCommand(helpMeCommand);
program.addCommand(deployCheckCommand);
program.addCommand(compareToolsCommand);
program.addCommand(onboardCommand);
program.addCommand(slackReportCommand);
program.addCommand(hotspotsCommand);
program.addCommand(whatIfCommand);
program.addCommand(gitStatsCommand);
program.addCommand(topCommand);
program.addCommand(whyCommand);
program.addCommand(jiraCommand);
program.addCommand(profileCommand);
program.addCommand(ignoreCommand);
program.addCommand(gitlabCommand);
program.addCommand(scorecardCommand);
program.addCommand(suggestCommand);
program.addCommand(githubActionCommand);
program.addCommand(leaderboardCommand);
program.addCommand(setupHooksCommand);
program.addCommand(dockerCommand);
program.addCommand(forecastCommand);
program.addCommand(quickCommand);
program.addCommand(markdownReportCommand);

program.parse();
