export function safeDiv(numerator: number, denominator: number): number | null {
  if (denominator === 0) return null;
  return numerator / denominator;
}

export function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max);
}

export function toPercent(value: number | null): string {
  if (value === null) return 'N/A';
  return `${(value * 100).toFixed(1)}%`;
}

export function isAiPr(labels: string[], commitMessages: string[]): boolean {
  const AI_LABELS = ['ai-generated', 'ai-assisted', 'copilot', 'cursor', 'ai-coded'];
  const AI_KEYWORDS = ['generated by ai', 'ai-generated', 'copilot', 'cursor', 'ai assisted'];

  const hasAiLabel = labels.some((label) =>
    AI_LABELS.some((al) => label.toLowerCase().includes(al)),
  );

  const hasAiCommit = commitMessages.some((msg) =>
    AI_KEYWORDS.some((kw) => msg.toLowerCase().includes(kw)),
  );

  return hasAiLabel || hasAiCommit;
}

export function formatDate(date: Date): string {
  return date.toISOString().split('T')[0] ?? '';
}
