import { describe, it, expect } from 'vitest';
import { safeDiv, clamp, toPercent, isAiPr, formatDate } from './index.js';

describe('safeDiv', () => {
  it('should divide correctly', () => {
    expect(safeDiv(10, 2)).toBe(5);
  });

  it('should return null for zero denominator', () => {
    expect(safeDiv(10, 0)).toBeNull();
  });
});

describe('clamp', () => {
  it('should clamp values', () => {
    expect(clamp(5, 0, 10)).toBe(5);
    expect(clamp(-1, 0, 10)).toBe(0);
    expect(clamp(15, 0, 10)).toBe(10);
  });
});

describe('toPercent', () => {
  it('should format percentage', () => {
    expect(toPercent(0.856)).toBe('85.6%');
  });

  it('should return N/A for null', () => {
    expect(toPercent(null)).toBe('N/A');
  });
});

describe('isAiPr', () => {
  it('should detect AI labels', () => {
    expect(isAiPr(['ai-generated'], [])).toBe(true);
    expect(isAiPr(['bug-fix'], [])).toBe(false);
  });

  it('should detect AI commit messages', () => {
    expect(isAiPr([], ['Generated by AI assistant'])).toBe(true);
    expect(isAiPr([], ['fix: normal commit'])).toBe(false);
  });
});

describe('formatDate', () => {
  it('should format date to YYYY-MM-DD', () => {
    expect(formatDate(new Date('2026-02-25T12:00:00Z'))).toBe('2026-02-25');
  });
});
